# Generated by Django 2.0.3 on 2018-05-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRecord', models.TextField()),
                ('lineusrid', models.TextField()),
                ('clientid', models.TextField(default='-1')),
                ('clientnum', models.TextField(default='-1')),
                ('takeMedecine', models.IntegerField(default=0)),
                ('changeMedecine', models.IntegerField(default=0)),
                ('docfile', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'Document',
            },
        ),
    ]
